ejemplo(1,no,[cielo=soleado,temperatura=alta,humedad=alta,viento=debil]).
ejemplo(2,no,[cielo=soleado,temperatura=alta,humedad=alta,viento=fuerte]).
ejemplo(3,si,[cielo=nublado,temperatura=alta,humedad=alta,viento=debil]).
ejemplo(4,si,[cielo=lluvioso,temperatura=templada,humedad=alta,viento=debil]).
ejemplo(5,si,[cielo=lluvioso,temperatura=fresca,humedad=normal,viento=debil]).
ejemplo(6,no,[cielo=lluvioso,temperatura=fresca,humedad=normal,viento=fuerte]).
ejemplo(7,si,[cielo=nublado,temperatura=fresca,humedad=normal,viento=fuerte]).
ejemplo(8,no,[cielo=soleado,temperatura=templada,humedad=alta,viento=fuerte]).
ejemplo(9,si,[cielo=soleado,temperatura=fresca,humedad=normal,viento=debil]).
ejemplo(10,si,[cielo=lluvioso,temperatura=templada,humedad=normal,viento=debil]).
ejemplo(11,si,[cielo=soleado,temperatura=nublado,humedad=normal,viento=fuerte]).
ejemplo(12,si,[cielo=nublado,temperatura=templado,humedad=alta,viento=fuerte]).
ejemplo(13,si,[cielo=nublado,temperatura=alta,humeda=normal,viento=debil]).
ejemplo(14,no,[cielo=lluvioso,temperatura=templada,humedad=alta,viento=fuerte]).
